In [25]:
import numpy as np

In [26]:
# 10자리 연속된 array 생성
arr = np.arange(10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# 5번째 자리를 출력
arr[5]

np.int64(5)

In [29]:
# 5~8 까지의 값 출력
arr[5:8]

array([5, 6, 7])

In [30]:
# 5에서 8까지의 값들은 12로 변경
arr[5:8]=12

In [31]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
# 전체 출력
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

# 2차원 array 인덱싱

In [33]:
arr2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

In [34]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
# 2행의 전체값 가져오기 
arr2[2, :]

array([ 9, 10, 11, 12])

In [37]:
# 1행~2행의 전체값 가져오기
arr2[1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
# 전체 행을 가져오되, 마지막 열 값만 가져오기
arr2[:, 3]

array([ 4,  8, 12, 16])

In [39]:
# 0~1행까지 1~2열까지의 값만 가져오기 -> 직접 해보세요
arr2[0:2, 1:3]

array([[2, 3],
       [6, 7]])

# 불리언 인덱싱

In [44]:
# 7개의 이름 array 생성
names = np.array(['AAA','BBB','CCC','AAA','BBB','CCC','CCC'])
# 7행 4열의 랜덤한 숫자 데이터 생성
data = np.random.randn(7,4)

In [42]:
names

array(['AAA', 'BBB', 'CCC', 'AAA', 'BBB', 'CCC', 'CCC'], dtype='<U3')

In [43]:
data

array([[-0.08686789, -1.81187227, -0.72824007, -0.63727264],
       [ 1.54576143, -0.08830436, -0.43531768, -0.44075692],
       [-0.35348818, -2.19298271, -2.007829  , -0.22932757],
       [ 0.06130729, -0.21170673, -0.89269715, -0.9189802 ],
       [-0.39577849, -0.61085073,  0.71318054, -0.21606314],
       [ 0.99937996, -1.17421612, -1.14606533,  1.30347515],
       [ 1.18574646, -1.34025452,  0.0603814 ,  0.05469899]])

boolean은 names array와 data array의 각 행에 순서대로 위치가 대응된다고 가정하고 인덱싱 진행

In [46]:
# CCC에 해당되는 값만 True로 출력된다
names == 'CCC'

array([False, False,  True, False, False,  True,  True])

In [49]:
# data에서 검색함. data에서 names가 CCC인 행(3,6,7 번째 행)의 값에 해당되는 전체 열값들만 쭉 가져옴.
data[names=='CCC', :]

array([[ 3.80811235,  0.10168136, -0.3200351 , -1.2237238 ],
       [-1.18057402,  0.15425364, -0.02986838, -1.72993468],
       [ 0.489597  , -0.12329995, -0.84005235,  0.77581251]])

In [50]:
data[names=='AAA', :]

array([[ 0.24412805,  1.80173555,  0.08520887,  2.26756382],
       [ 0.35271728, -0.17087797, -0.08588637, -0.38343624]])

In [52]:
# aaa 또는 ccc의 마스크를 이용하여 array 인덱싱하기
data[(names=='AAA')|(names=='CCC'), :]

array([[ 0.24412805,  1.80173555,  0.08520887,  2.26756382],
       [ 3.80811235,  0.10168136, -0.3200351 , -1.2237238 ],
       [ 0.35271728, -0.17087797, -0.08588637, -0.38343624],
       [-1.18057402,  0.15425364, -0.02986838, -1.72993468],
       [ 0.489597  , -0.12329995, -0.84005235,  0.77581251]])

In [53]:
# 조건부 마스크 (맨 마지막 열에서 0보다 작은것) - 작은지 확인
data[:, 3]<0


array([False, False,  True,  True,  True,  True, False])

In [54]:
# 치환 (데이타 인덱싱 할때 마지막 열의 값이 0보다 작은것들은 1로 치환한다.)
data[data[:,3] <0, :]=1

In [55]:
data

array([[ 0.24412805,  1.80173555,  0.08520887,  2.26756382],
       [ 1.83950535,  2.07984812, -0.11123531,  0.89503233],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.489597  , -0.12329995, -0.84005235,  0.77581251]])