In [25]:
import numpy as np

In [26]:
# 10자리 연속된 array 생성
arr = np.arange(10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# 5번째 자리를 출력
arr[5]

np.int64(5)

In [29]:
# 5~8 까지의 값 출력
arr[5:8]

array([5, 6, 7])

In [30]:
# 5에서 8까지의 값들은 12로 변경
arr[5:8]=12

In [31]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
# 전체 출력
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

# 2차원 array 인덱싱

In [33]:
arr2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

In [34]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
# 2행의 전체값 가져오기 
arr2[2, :]

array([ 9, 10, 11, 12])

In [37]:
# 1행~2행의 전체값 가져오기
arr2[1:3, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
# 전체 행을 가져오되, 마지막 열 값만 가져오기
arr2[:, 3]

array([ 4,  8, 12, 16])

In [39]:
# 0~1행까지 1~2열까지의 값만 가져오기 -> 직접 해보세요
arr2[0:2, 1:3]

array([[2, 3],
       [6, 7]])

# 불리언 인덱싱