In [1]:
import numpy as np

In [5]:
arr = np.arange(1, 10) # 1~10 연속숫자
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.square(arr) # 각 성분 제곱근 계산

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
np.log10(arr) # 각 성분의 log10 값 계산

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

** numpy에서 두 개의 array의 각 성분에 적용되는 함수 **
- add, subtract, multiply, divide, maximum, minimum

In [10]:
# 2개 ARRAY 랜덤하게 8개씩 생성
x = np.random.randn(8)
y = np.random.randn(8)

In [11]:
x

array([ 0.62515668,  0.08723949, -1.31925544, -1.38040367, -0.07267221,
        0.29112661,  0.73234056,  0.47720911])

In [12]:
y

array([-1.03802813,  1.92037277,  1.02893577,  2.42883336,  1.60783971,
       -0.29917288, -0.00452907,  0.1682419 ])

In [13]:
# x와 y의 위치값을 비교하여 maximum을 수행
np.maximum(x, y)

array([0.62515668, 1.92037277, 1.02893577, 2.42883336, 1.60783971,
       0.29112661, 0.73234056, 0.47720911])

** 통계 함수 **
- sum, mean, std/var, min/max, argmin/argmax, cumsum, cumprod

In [15]:
arr = np.random.randn(5,4)
arr

array([[-0.10507113, -0.07707102,  0.18640378,  0.22114149],
       [ 0.69963246, -0.69679299, -0.62162529, -0.95231955],
       [ 0.71706474, -1.18912128,  1.99411815, -0.62869889],
       [-1.19481825, -0.07096034,  0.84407875, -0.03146175],
       [-1.10562727, -1.58906648,  0.79959374,  0.26236237]])

In [16]:
# arr array의 모든 값들을 더한 값 구하기. (sum)
arr.sum()

np.float64(-2.5382387563551574)

In [18]:
arr.mean() # 평균 값

np.float64(-0.12691193781775786)

In [19]:
# 행 방향으로 열 값들을 전체 sum 수행 (각 열의 합 계산)
arr.sum(axis=0)

array([-0.98881946, -3.6230121 ,  3.20256913, -1.12897633])

In [20]:
# 열 방향으로 행의 값들을 전체 sum 수행 (각 행의 합 계산)
arr.sum(axis=1)

array([ 0.22540312, -1.57110537,  0.89336273, -0.45316159, -1.63273764])

In [21]:
# 조건부 연산
arr > 0

array([[False, False,  True,  True],
       [ True, False, False, False],
       [ True, False,  True, False],
       [False, False,  True, False],
       [False, False,  True,  True]])

In [22]:
# true값
(arr>0).sum()

np.int64(8)

# 정렬 함수 및 기타 함수

In [23]:
arr = np.random.randn(10)
arr

array([-1.29295614,  0.37711301, -0.27905972, -0.15801599,  0.75833886,
        0.31314132,  0.09481069,  0.93355039,  0.20134536, -0.39377565])

In [25]:
# 10개 데이터 오름차순 정렬
np.sort(arr)

array([-1.29295614, -0.39377565, -0.27905972, -0.15801599,  0.09481069,
        0.20134536,  0.31314132,  0.37711301,  0.75833886,  0.93355039])

In [27]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([ 0.93355039,  0.75833886,  0.37711301,  0.31314132,  0.20134536,
        0.09481069, -0.15801599, -0.27905972, -0.39377565, -1.29295614])

In [28]:
# 2차원 array 정렬
arr = np.random.randn(5,3) #5행3열
arr

array([[-0.5383367 , -0.34264696,  0.09605044],
       [-0.32152377,  0.23111365, -0.73347706],
       [ 1.53715583,  1.6272654 , -0.59175494],
       [-0.36459669,  1.08291764, -0.61728557],
       [-1.0138147 , -1.21823303,  1.81319348]])

2차원 array를 정의, axis=0을 설정하면 행방향으로 오름차순 정렬, axis=1 설정하면 열방향으로 오름차순 정렬이 수행된다.

In [29]:
# 행방향으로 열의 값을 오름차순 정렬
np.sort(arr, axis=0)

array([[-1.0138147 , -1.21823303, -0.73347706],
       [-0.5383367 , -0.34264696, -0.61728557],
       [-0.36459669,  0.23111365, -0.59175494],
       [-0.32152377,  1.08291764,  0.09605044],
       [ 1.53715583,  1.6272654 ,  1.81319348]])

In [30]:
# 열방향으로 행의 값을 오름차순 정렬
np.sort(arr, axis=1)

array([[-0.5383367 , -0.34264696,  0.09605044],
       [-0.73347706, -0.32152377,  0.23111365],
       [-0.59175494,  1.53715583,  1.6272654 ],
       [-0.61728557, -0.36459669,  1.08291764],
       [-1.21823303, -1.0138147 ,  1.81319348]])

In [ ]:
# 길이가 아주 긴 array가 있을 때, 상위 5%에 위치하는 값을 찾기 (이런 것도 많이 한다)
1. 데이터 생성 및 내림차순 정렬
2. 5%에 해당하는 위치값을 찾고, 해당하는 값을 가져오면 된다.

In [35]:
large_arr = np.random.randn(150)
large_arr

array([-0.09066549, -0.13557695,  0.6344547 , -0.14239041,  0.51171325,
       -0.49578363,  0.2964514 ,  1.93131608,  1.03742855,  0.18495048,
        0.00468765,  0.86435175,  0.5849132 , -0.3718789 ,  0.617099  ,
        0.69980175,  0.02853692,  1.01484037,  0.45458027,  0.70915821,
        0.05450364, -1.21194871,  0.73925571,  0.43859193,  0.28603546,
        0.04437725, -0.18454315, -1.53850697,  0.716842  , -1.33705325,
       -0.41932811,  0.74773404, -0.88505247, -0.72079223,  1.19344807,
       -1.42824064, -1.90174503,  1.77876667,  3.44228406, -0.39258065,
       -0.03301126, -0.18811823, -0.64036665, -1.16475928, -0.95705954,
       -0.62296155,  0.26635289, -1.35056214,  1.35381248, -1.18497887,
        0.42237766,  0.60331875,  1.59275811,  0.0664959 , -1.9511137 ,
        0.23887221, -0.74449458,  0.18574976, -0.58612628,  0.49050164,
        0.71936068,  0.17839094,  0.75397696,  0.00384256, -1.32052936,
       -1.24576775,  1.34426141,  1.07976823, -1.0270593 ,  1.17

In [37]:
# 내림차순 정렬
np.sort(large_arr)[::-1]

array([ 3.44228406,  2.82032906,  2.26067486,  1.93131608,  1.77876667,
        1.66725189,  1.59275811,  1.43092065,  1.35381248,  1.34426141,
        1.29198372,  1.2419584 ,  1.21603971,  1.19344807,  1.17056078,
        1.12605988,  1.1076402 ,  1.09141467,  1.07976823,  1.03742855,
        1.0351563 ,  1.02095783,  1.01484037,  0.96864335,  0.90816987,
        0.86435175,  0.84473558,  0.83151022,  0.82865444,  0.76175513,
        0.75397696,  0.74773404,  0.73925571,  0.71936068,  0.716842  ,
        0.70915821,  0.70664665,  0.69980175,  0.68836464,  0.68404421,
        0.66848091,  0.64384934,  0.64166103,  0.6344547 ,  0.6266576 ,
        0.617099  ,  0.60331875,  0.5849132 ,  0.52471547,  0.51171325,
        0.49050164,  0.47537797,  0.45458027,  0.43859193,  0.43502017,
        0.42237766,  0.34002895,  0.2964514 ,  0.28603546,  0.27153566,
        0.26844716,  0.26635289,  0.25625509,  0.24152486,  0.23887221,
        0.23816365,  0.2380174 ,  0.22263957,  0.20038646,  0.18

In [40]:
# 상위 5%에 해당하는 값 찾기
# 0.05*150 # 7.5
# 내림차순된 array에서 0.05*150 을 수행하여 int값으로 변경. 계산된 7번째 자리값이 상위 5%의 값이다.
np.sort(large_arr)[::-1][int(0.05*len(large_arr))]

np.float64(1.4309206529151106)

In [42]:
# 중복된 값 제거하기 - unique()
names = np.array(['aaa','aaa','aaa','fff','fff','ddd', 'eee'])
ints = np.array([3,3,3,4,4,1,1,2,2,5,5,6,8,8])

In [43]:
np.unique(names)

array(['aaa', 'ddd', 'eee', 'fff'], dtype='<U3')

In [44]:
np.unique(ints)

array([1, 2, 3, 4, 5, 6, 8])