In [1]:
import numpy as np

In [4]:
data = np.genfromtxt('./data/ratings.dat', delimiter='::', dtype=np.int64)
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], shape=(1000209, 4))

In [5]:
# 데이터 컬럼 내용 (user_id::item::rating::timestamp)
# 5행까지 확인
data[:5,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]])

In [6]:
data.shape

(1000209, 4)

In [ ]:
# 문제) 3열의 전체 평균 평점 계산하기.

In [13]:
mean_rating_total = data[:, 2].mean()
mean_rating_total

np.float64(3.581564453029317)

In [ ]:
# 문제) 사용자 별 평균 평점 계산하기 - 중복제거도?? 

In [16]:
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], shape=(1000209, 4))

In [25]:
(data[0]==user)

array([ True, False, False, False])

In [26]:
# 3행 값을 가져오되, 1행에 
# user = 1
# data[2, (data[1,:]==user)].mean()
# data
# data[:,2]=(data[0]==user) # user에 해당하는 3열 가져오기

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], shape=(1000209, 4))

In [37]:
# 일단 행을 가져옴. user인 행을 가져옴.
user = 1
data[data[:,0]==user,2].mean() # 1번 열이 해당 유저인 모든 스코어를 가져옴. + mean으로 평균화함 => 해당 유저의 평균점수

np.float64(4.188679245283019)

In [ ]:
# 해당 유저의 평균점수 는 구했는데 각 사용자 별 평균 평범은 ??
# 그리고 

In [38]:
# 문제) 사용자 별 평균 평점 계산하기 - 정답

In [41]:
# user에 대해 unique 값만 먼저 다 저장한다.
user_id_arr = np.unique(data[:,0])
user_id_arr

array([   1,    2,    3, ..., 6038, 6039, 6040], shape=(6040,))

In [42]:
# 유저 몇개인지 확인
user_id_arr.shape

(6040,)

In [45]:
# 빈 리스트를 생성 -> 여기에 연산해서 나오는 결과 넣을 것
mean_rating_by_user_list = []

for user_id in user_id_arr:
    data_for_user = data[data[:,0]==user_id, :] # 해당 유저의 데이터. 특정 USER_ID 값들의 ARRAY를 저장한 변수 (unique 값 별로 저장될것이다.)
    mean_rating_for_user = data_for_user[:, 2].mean() # 해당 id 에 대한 평균 평점을 계산한다.
    mean_rating_by_user_list.append([user_id, mean_rating_for_user]) # 빈 리스트에 결과를 넣는다.

In [46]:
data_for_user[:10]

array([[     6040,       573,         4, 956704056],
       [     6040,       589,         4, 956704996],
       [     6040,         1,         3, 957717358],
       [     6040,      2068,         4, 997453982],
       [     6040,       592,         2, 956716016],
       [     6040,       593,         5, 956703954],
       [     6040,      3016,         2, 956716157],
       [     6040,      3017,         1, 956716519],
       [     6040,      2070,         4, 956715676],
       [     6040,      1419,         3, 956704056]])

In [47]:
mean_rating_by_user_list[:10]

[[np.int64(1), np.float64(4.188679245283019)],
 [np.int64(2), np.float64(3.7131782945736433)],
 [np.int64(3), np.float64(3.9019607843137254)],
 [np.int64(4), np.float64(4.190476190476191)],
 [np.int64(5), np.float64(3.1464646464646466)],
 [np.int64(6), np.float64(3.9014084507042255)],
 [np.int64(7), np.float64(4.32258064516129)],
 [np.int64(8), np.float64(3.884892086330935)],
 [np.int64(9), np.float64(3.7358490566037736)],
 [np.int64(10), np.float64(4.114713216957606)]]

In [ ]:
# 배열 안에 배열로 순서대로 [[유저아이디, 평점], [유저아이디2, 평점]] 이렇게 하라는 거였음.

In [48]:
print(mean_rating_by_user_list[:10])

[[np.int64(1), np.float64(4.188679245283019)], [np.int64(2), np.float64(3.7131782945736433)], [np.int64(3), np.float64(3.9019607843137254)], [np.int64(4), np.float64(4.190476190476191)], [np.int64(5), np.float64(3.1464646464646466)], [np.int64(6), np.float64(3.9014084507042255)], [np.int64(7), np.float64(4.32258064516129)], [np.int64(8), np.float64(3.884892086330935)], [np.int64(9), np.float64(3.7358490566037736)], [np.int64(10), np.float64(4.114713216957606)]]


In [49]:
# csv 파일에 결과 저장

In [53]:
# 리스트 => array 타입으로 변환
mean_rating_by_user_list_array = np.array(mean_rating_by_user_list, dtype=np.float64) # array 타입으로 변환
mean_rating_by_user_list_array.shape

(6040, 2)

In [57]:
# 파일에 저장 .savetxt("저장경로", 저장할array, 포맷, delimiter=구분인자)
np.savetxt("./data/2-04) mean_rating_by_user.csv", mean_rating_by_user_list_array, fmt="%.3f", delimiter=',')